### PR TITLE
Add `--wait` option to Helm install/upgrade in CI

### PR DESCRIPTION
**Pull request by ldevulder**
This could help to "resolve" sporadic issues we have sometimes in Public Cloud CI. Some of them are because the helm command finish too quickly.

### CODE REVIEW

**Comment by olblak** [comment]
Would it make sense to use a different timeout value than the default 5min

**Comment by olblak** [comment]
The reason why I am asking is that sometimes it takes more than 5minutes to create provision loadbalancers.
It could make sense to increase the timeout value to 10min

**Comment by ldevulder** [comment]
> The reason why I am asking is that sometimes it takes more than 5minutes to create provision loadbalancers.

Not sure that waiting for more than 5 minutes is a good idea, and anyway I added code to test that we get an IP for the LB. As in RKE for example we can't have LB configured after Traefik installation, as the LB (metallb) is installed after.

**Review by olblak — APPROVED** [review]

**Comment by ldevulder** [comment]
EKS issue is something else, it will be invested separately.

**Pull request merged**
