### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mysticaltech**
Python is now supported out of the box.

### CODE REVIEW

**Comment by mysticaltech** [comment]
ksnip_20220624-110732

**Comment by mysticaltech** [comment]
@jimmykarily Exactly, but the link in the readme leads to a 404.

This PR was just to bring the above to your attention! Don't hesitate to close it now that you know, and keep up the good work.

**Review by jimmykarily — APPROVED** [review]

**Comment by jimmykarily** [comment]
I'm merging this. Will fix docs (move the page to docs.epinio.io and change wording) in another PR. Thanks @mysticaltech !

**Comment by jimmykarily** [comment]
Removed more relics here: https://github.com/epinio/epinio/pull/1617

**Comment by jimmykarily** [comment]
Docs PR: https://github.com/epinio/docs/pull/147

**Pull request merged**
