### PR TITLE
Create epinio rpm

### PR DESCRIPTION
**Pull request by malcolmlewis**
Add howto to build an epinio rpm and include the rpm spec file.

### CODE REVIEW

**Comment by kkaempf** [comment]
Hmm, wouldn't it be simpler to build the RPM in Open Build Service, so we can target multiple distributions, have better control over the build, and produce signed packages ?

**Comment by malcolmlewis** [comment]
> Hmm, wouldn't it be simpler to build the RPM in Open Build Service, so we can target multiple distributions, have better control over the build, and produce signed packages ?
Hi
Yes, but there are multiple go packages as dependencies to build which will also need maintenance... but is doable.

**Comment by kkaempf** [comment]
> > Yes, but there are multiple go packages as dependencies to build which will also need maintenance... but is doable.

Don't worry about dependencies. Run `go mod vendor` (with go > 1.13 iirc) and add the resulting `vendor/` dir as a tarball.

See the [minikube package](https://build.opensuse.org/package/show/Virtualization:containers/minikube) as an example.

**Comment by malcolmlewis** [comment]
> > > Yes, but there are multiple go packages as dependencies to build which will also need maintenance... but is doable.
> 
> Don't worry about dependencies. Run `go mod vendor` (with go > 1.13 iirc) and add the resulting `vendor/` dir as a tarball.
> 
> See the [minikube package](https://build.opensuse.org/package/show/Virtualization:containers/minikube) as an example.

Hi
Tried both as a service and manual run, neither work :(

``` go mod vendor
go: finding module for package github.com/epinio/epinio/assets/statikWebAssets
go: finding module for package github.com/epinio/epinio/assets/statik
go: finding module for package github.com/epinio/epinio/assets/statikWebViews
github.com/epinio/epinio/helpers imports
	github.com/epinio/epinio/assets/statik: no matching versions for query "latest"
github.com/epinio/epinio/internal/filesystem imports
	github.com/epinio/epinio/assets/statikWebAssets: no matching versions for query "latest"
github.com/epinio/epinio/internal/filesystem imports
	github.com/epinio/epinio/assets/statikWebViews: no matching versions for query "latest"
```

```
osc service run
INFO:obs-service-go_modules:Autodetecting archive since no archive param provided in _service
INFO:obs-service-go_modules:Archive autodetected at /data/obs/home:malcolmlewis:TESTING/epinio/epinio-v0.0.18.tar.gz
INFO:obs-service-go_modules:Using archive epinio-v0.0.18.tar.gz
INFO:obs-service-go_modules:Running OBS Source Service: obs-service-go_modules
INFO:obs-service-go_modules:Extracting epinio-v0.0.18.tar.gz to /data/obs/home:malcolmlewis:TESTING/epinio/tmpcofiymvs.go_modules.service
INFO:obs-service-go_modules:Using go.mod found at /data/obs/home:malcolmlewis:TESTING/epinio/tmpcofiymvs.go_modules.service/epinio-0.0.18/go.mod
INFO:obs-service-go_modules:go mod download
INFO:obs-service-go_modules:go mod verify
INFO:obs-service-go_modules:all modules verified
INFO:obs-service-go_modules:go mod vendor
go: finding module for package github.com/epinio/epinio/assets/statikWebViews
go: finding module for package github.com/epinio/epinio/assets/statik
go: finding module for package github.com/epinio/epinio/assets/statikWebAssets
github.com/epinio/epinio/helpers imports
	github.com/epinio/epinio/assets/statik: no matching versions for query "latest"
github.com/epinio/epinio/internal/filesystem imports
	github.com/epinio/epinio/assets/statikWebAssets: no matching versions for query "latest"
github.com/epinio/epinio/internal/filesystem imports
	github.com/epinio/epinio/assets/statikWebViews: no matching versions for query "latest"
INFO:obs-service-go_modules:Vendor go.mod dependencies to vendor.tar.gz
Traceback (most recent call last):
  File "/usr/lib/obs/service/go_modules", line 174, in <module>
    main()
  File "/usr/lib/obs/service/go_modules", line 163, in main
    tar.add(vendor_dir, arcname=("vendor"))
  File "/usr/lib64/python3.8/tarfile.py", line 1955, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib64/python3.8/tarfile.py", line 1834, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/data/obs/home:malcolmlewis:TESTING/epinio/tmpcofiymvs.go_modules.service/epinio-0.0.18/vendor'
Aborting: service call failed:  /usr/lib/obs/service/go_modules --outdir /data/obs/home:malcolmlewis:TESTING/epinio/tmpcofiymvs.go_modules.service
```

**Comment by malcolmlewis** [comment]
@kkaempf making progress https://build.opensuse.org/package/show/home:malcolmlewis:TESTING/epinio

**Comment by kkaempf** [comment]
> @kkaempf making progress https://build.opensuse.org/package/show/home:malcolmlewis:TESTING/epinio

I'd vote to close this PR in favor of Open Build Service packages :wink:

**Comment by malcolmlewis** [comment]
Closing this request as able to build on OBS now.

**Pull request closed without merging**
