### PR TITLE
Chore: disable version tracking/reporting in the scenario CI flows.

### PR DESCRIPTION
**Pull request by andreas-kupries**
Pulled out of the abandoned #2113.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
Upgrade failure is

>  Error: failed to parse prev-values.yaml: error converting YAML to JSON: yaml: mapping values are not allowed in this context

The referenced `prev-values.yaml` is created by the test case itself, via `helm get values epinio -n epinio`. looking at the result of this command in a local setup shows that the issue is likely the generated header line. See

```
USER-SUPPLIED VALUES:
containerregistry:
  enabled: false
global:
...
```

An additional `-o yaml` seems to fix that.

**Comment by andreas-kupries** [comment]
golangci-lint :boom: yet I see no error messages

**Comment by andreas-kupries** [comment]
Still parsing issues ... Showing actual data in the log:

```
Old values = ((WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
  containerregistry:
    enabled: false
  global:
...
```

Lovely. We get the warning written to the yaml we want.

**Comment by enrichman** [comment]
I'm curious to know if we really (still) need that, and why. Maybe it was for an old RKE version? Or a workaround?
- https://github.com/rancher/rke/issues/2395

**Comment by andreas-kupries** [comment]
> I'm curious to know if we really (still) need that, and why. Maybe it was for an old RKE version? Or a workaround?
> 
>     * [RKE cli should generate kube config with 0600 permissions rancher/rke#2395](https://github.com/rancher/rke/issues/2395)

AFAICT from the comments in the script the default is to create the file with secure permissions, i.e `600`.
As this is done by a root process (see all the `sudo`'s) the resulting file will not be readable by helm, kubectl from the rest of the CI steps. Thus the code instructs RKE to make it insecure, to actually have it accessible.

And the warnings are simply ignored

What now happened was that these warning got into the output of `helm get values`. Even if we ask specifically for yaml output. With the warnings in the yaml it was not yaml any longer and the `helm upgrade` broke entirely.

My fix is to make a local copy of the file (possible due to insecure permissions), make that copy secure, and use that as the kubeconfig. No more warnings, no more broken yaml.

**Review by enrichman — APPROVED** [review]

**Pull request merged**
