### PR TITLE
Updated to Go version 1.20.4

### LINKED ISSUE #2196: Update Go 1.20
Update Go version to `1.20`

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #2196

### CODE REVIEW

**Review by enrichman — CHANGES_REQUESTED** [review]
Go `v1.20.4` was released yesterday https://github.com/golang/go/releases/tag/go1.20.4

We should update to it!

**Comment by andreas-kupries** [comment]
Of course they did. Ok. Will do. Will also rebase to the latest main with the CI rework to help with rate limits.

**Comment by andreas-kupries** [comment]
Bump to .4, with commit ced730b3a0056f332ee47f05d46053f2f95afac1.
Rebased atop of CI cred work.

**Review by enrichman — APPROVED** [review]

**Comment by andreas-kupries** [comment]
Rebased atop partial revert of CI changes

**Pull request merged**
