### PR TITLE
import tls issuer mail work, and lots of ui/dependency updates

### PR DESCRIPTION
**Pull request by andreas-kupries**
Ticket ref  https://github.com/epinio/helm-charts/issues/348
Chart PR ref https://github.com/epinio/helm-charts/pull/370
Documentation ref https://github.com/epinio/docs/pull/214

### CODE REVIEW

**Review by enrichman — CHANGES_REQUESTED** [review]
The PR #2084 is failing because of #2085.
And this one is failing for the same reason.

I've found the problem and I'm going to open a PR, so we can rebase the other and this one with the fix! :pray:

**Comment by andreas-kupries** [comment]
> And this one is failing for the same reason.

I suspected. Awaiting your fix.

**Comment by enrichman** [comment]
Thanks, opened PR https://github.com/epinio/helm-charts/pull/373

**Review by enrichman — APPROVED** [review]

**Comment by enrichman** [comment]
This should contain all the https://github.com/epinio/epinio/pull/2084, so it's fine for me to merge this in favor of the other one.

**Pull request merged**
