### PR TITLE
CI: use letsencrypt-staging

### LINKED ISSUE #950: Use staging for letsencrypt cert in CI
Because there are limitations/quotas with the production one, and we hit these limitations regularly.

### PR DESCRIPTION
**Pull request by ldevulder**
This is to bypass the quotas on letsencrypt-production.

This should fix #950.

### CODE REVIEW

**Review by andreas-kupries — DISMISSED** [review]
lgtm

**Review by olblak — APPROVED** [review]

**Comment by ldevulder** [comment]
After a debugging session with @jimmykarily we found that epinio blocks in the `ANALYZING` part during the app deployment because `getRegistryCAHash` returns an empty hash, and this is because there is no `ca.crt` secret: https://github.com/epinio/epinio/blob/f6cacb5c9fbdcf67d475665414d5e4d20e49ab31/deployments/tekton.go#L315
There was a [bug](https://github.com/jetstack/cert-manager/issues/2111) for this but it has been closed (why?).

This is linked top the issue we had in the installer, see https://github.com/epinio/epinio/issues/1006#issuecomment-981381251.

**Comment by jimmykarily** [comment]
Since tekton only needs to trust the registry certificate (and not the CA in general), maybe we can fix it by mounting the registry certificate in the tekton pod. The certificate always exists, the CA may not (as explained in Loic's comment above).

We need to give that a try.

**Comment by jimmykarily** [comment]
> There was a [bug](https://github.com/jetstack/cert-manager/issues/2111) for this but it has been closed (why?).

This was their answer: https://github.com/jetstack/cert-manager/issues/1571#issuecomment-486661887 (on a relevant issue).
People seem to disagree, but they don't seem to care :D

**Comment by ldevulder** [comment]
Fixed by these PRs: https://github.com/epinio/epinio/pull/1082 and https://github.com/epinio/helm-charts/pull/43.

**Review by juadk — APPROVED** [review]
LGTM!

**Review by jimmykarily — APPROVED** [review]
AKS-CI is failing but we will fix it on another PR. Needs investigation, we can't reproduce it outside CI yet.

**Pull request merged**
