### PR TITLE
Dynamic silence and ingress type

### PR DESCRIPTION
**Pull request by manno**
Two small changes.

* Using the new ingress type for the api server. We used the new type already for workloads.
* Backfilling the silence fix for the "app create" PR

Fix for https://github.com/epinio/epinio/pull/553

### CODE REVIEW

**Review by andreas-kupries — APPROVED** [review]
Looks ok. I guess the ingress type changes are what came out of the discussion while I was out.

**Comment by manno** [comment]
> Looks ok. I guess the ingress type changes are what came out of the discussion while I was out.

Yes, we already use ingress v1 in other parts of the code base, so I fixed the TODO. However I typoed when I was unable to cherry pick https://github.com/epinio/epinio/commit/7721d610fdf27a79be980af522783671d3ffc198

**Review by rohitsakala — APPROVED** [review]

**Comment by manno** [comment]
I replace the remaining occurrences and fixed the epinio ingress commit.

**Review by rohitsakala — APPROVED** [review]

**Review by andreas-kupries — APPROVED** [review]
lgtm

**Pull request merged**
