### PR TITLE
fix: attempt to retrieve stage id of an app without workload

### LINKED ISSUE #536: Scaling an app to zero prevents epinio from working
If you scale down an app with `epinio app update --instances 0` to zero, epinio is not able to fix it afterwards because it can not connect anymore.

This can be fixed manually by using k9s to increase the replicas.

It should be possible to scale to zero to basically pause an app, and it is possible when done directly in k9s.

## Acceptance criteria
* Scaling down an app to 0 is possible
* The app can be scaled up again with epinio

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fixes #536.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
Ok. The CI failures look to be an actual issue in my PR.
It seems that my changes somehow disabled the `--staging` option of `app logs`.
I get the same logs with and without it in my local trial.

Investigating ... :construction: Back to `in progress` ...

**Comment by andreas-kupries** [comment]
Right, the system needs the `stageId`, and is not getting the correct value, but an empty string ... And that points directly to my changes in the retrieval of same!

**Comment by andreas-kupries** [comment]
The original claim that the stageID can be pulled out of the deployment is incorrect. There is no such label on the deployment.
The pod does have it, `epinio.suse.org/stage-id: e4e5b5cb34515edf` for the app I am looking at.

Huh ... Closer look ... Found it ... `spec.template.metadata.labels`. Of course. The pod spec carried by the deployment.
Ok. Lets read it from that field.

**Comment by andreas-kupries** [comment]
Local CI focused on the failing test cases is now :heavy_check_mark:

**Review by rohitsakala — APPROVED** [review]

**Pull request merged**
