### PR TITLE
CI: bring back acceptance-install tests

### PR DESCRIPTION
**Pull request by ldevulder**
For now, this is the better way to test epinio server changes quickly.
It also re-allows running Public Cloud tests nightly.

Next step will be:
- try to either add or move these tests in epinio-helm-chart repo
- add differents tests in epinio-helm-chart repo to specifically
  test thes changes in the Helm charts

Related to: https://github.com/epinio/epinio-helm-chart/issues/15

### CODE REVIEW

**Comment by ldevulder** [comment]
There are errors with `letsencrypt-production` that seem to be more related to epinio itself:
```
2021/12/10 11:59:20 EpinioApiClient "msg"="response is not StatusOK" "error"="Internal Server Error: PipelineRun tekton-staging parameters is missing some parameters required by Pipeline 531a27bdf52908a9's parameters: PipelineRun missing parameters: [REGISTRY_CERTIFICATE_SECRET REGISTRY_CERTIFICATE_HASH]" "status"=500
```
I think I will open new issue for this.

**Comment by jimmykarily** [comment]
> There are errors with `letsencrypt-production` that seem to be more related to epinio itself:
> 
> ```
> 2021/12/10 11:59:20 EpinioApiClient "msg"="response is not StatusOK" "error"="Internal Server Error: PipelineRun tekton-staging parameters is missing some parameters required by Pipeline 531a27bdf52908a9's parameters: PipelineRun missing parameters: [REGISTRY_CERTIFICATE_SECRET REGISTRY_CERTIFICATE_HASH]" "status"=500
> ```
> 
> I think I will open new issue for this.

I had that locally, iirc the problem was that the epinio helm chart used in the epinio-installer helm chart was old but I could be wrong.

**Comment by ldevulder** [comment]
> I had that locally, iirc the problem was that the epinio helm chart used in the epinio-installer helm chart was old but I could be wrong.

I'm using the latest one. I will do manual tests today to see if I can debug the issue.

**Comment by ldevulder** [comment]
RKE, GKE and AKS fail because of an issue with the certificates in the helm charts, let's see this outside of this PR.

**Review by juadk — APPROVED** [review]

**Pull request merged**
