### PR TITLE
drop: standard platform API request

### LINKED ISSUE #2715: Drop hardcoded `CNB_PLATFORM_API=0.4` version
### Is your feature request related to a problem?

Issue:
Currently, if we want to use version `paketobuildpacks/builder-jammy-full:latest`we will face an error like:

```
failed to set platform API: platform API version '0.4' is incompatible with the lifecycle 
```
As to Epinio `v1.11.0-rc1` we are using as default version `paketobuildpacks/builder-jammy-full:0.3.290` which is hardcoded,

To use the `paketobuildpacks/builder-jammy-full:latest` we can use `--env CNB_PLATFORM_API=0.7` as @andreas-kupries  discovered:

```
epinio push -n cat -p /home/mmartin/suse/epinio-repos/epinio/assets/sample-app --builder-image paketobuildpacks/builder-jammy-full:latest --env CNB_PLATFORM_API=0.7
```

We should somehow discuss how to document this for this / future releases

### Solution you'd like

_No response_

### Alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #2715

### CODE REVIEW

**Comment by andreas-kupries** [comment]
The CI breakage shows that we need support in the staging scripts to handle an empty `appenv` directory, i.e. when an app has no EV's at all.

**Comment by enrichman** [comment]
Having a look at the Buildpack Platform spec this seems to be a required value:
- https://github.com/buildpacks/spec/blob/main/platform.md#platform-api-compatibility

They fallback to the 0.3 because it's the older without this need. The latest is the `0.12` ([Platform API v0.12](https://github.com/buildpacks/spec/releases/tag/platform%2Fv0.12)) but this breaking change seems a bit "scary to me":

> The concepts of stacks and mixins are removed in favor of existing constructs in the container image ecosystem such as operating system name, operating system version, and architecture (https://github.com/buildpacks/spec/pull/335, [RFC 096](https://github.com/buildpacks/rfcs/blob/main/text/0096-remove-stacks-mixins.md)).

The Paketo full builder is made with the concept of stacks, so I'm not sure it will work also with this latest API.

Having it hardcoded into Epinio doesn't seem a good option by the way.

Since this is related to the builder used imo makes sense to include it in the default-scripts, so it can be customized with different builder, without the user to explicitly know what to set, and why. It looks more build related, and having the use to explicitly set this basically everytime is very annoying.

**Review by enrichman — CHANGES_REQUESTED** [review]
I would save the user to know which "Platform API" should use, and for which builder, everytime.

Since it's needed and build-related I would make it explicit into the default-scripts.
I would try the `0.11` (not the very latest), and see how it works with our samples. :crossed_fingers:

**Comment by enrichman** [comment]
> > Since this is related to the builder used imo makes sense to include it in the default-scripts, so it can be customized with different builder, without the user to explicitly know what to set, and why. It looks more build related, and having the use to explicitly set this basically everytime is very annoying.
> 
> I will take a look into this possibility tomorrow.

@andreas-kupries thank you (missed the reply) :slightly_smiling_face:

**Comment by andreas-kupries** [comment]
> Since it's needed and build-related I would make it explicit into the default-scripts.

I would prefer to specify it in the config map outside of the script itself. To keep the scripts as shareable as possible.

An `env` key, whose value is a YAML string, so that I can at least pretend to have a properly nested map.

**Comment by enrichman** [comment]
> > Since it's needed and build-related I would make it explicit into the default-scripts.
> 
> I would prefer to specify it in the config map outside of the script itself. To keep the scripts as shareable as possible.
> 
> An `env` key, whose value is a YAML string, so that I can at least pretend to have a properly nested map.

That's even better. I forgot about the new specs.

I was thinking about something like:

```yaml
data:
  builder: "paketobuildpacks/builder-jammy-*:*"
  userID: "1001"
  groupID: "1000"
  base: epinio-stage-scripts
  env:
    - name: "CNB_PLATFORM_API"
      value: "0.11"
    - name: "FOO"
      value: "bar"
```

but then I realized that ConfigMaps are just key-value pairs, so I guess our best bet is going flat, as you said :slightly_smiling_face: 

```yaml
data:
  builder: "paketobuildpacks/builder-jammy-*:*"
  userID: "1001"
  groupID: "1000"
  base: epinio-stage-scripts
  env: |
    CNB_PLATFORM_API=0.11
    FOO=bar
```

**Comment by andreas-kupries** [comment]
Actually

```
env: |
    CNB_PLATFORM_API: "0.11"
    FOO: bar
```

**Comment by enrichman** [comment]
Yes, this encoding is less "standard" for env vars, but much easier to parse and check as a yaml. :smile:

**Review by enrichman — APPROVED** [review]
Just a small question but LGTM

**Comment by mmartin24** [comment]
Tested [here](https://github.com/epinio/epinio/issues/2715#issuecomment-1831797748) and working

**Pull request merged**
