### PR TITLE
feat: stream uploaded app sources directly into s3, without temp file

### PR DESCRIPTION
**Pull request by andreas-kupries**
ref #1113

### CODE REVIEW

**Review by enrichman — APPROVED** [review]
LGTM

I thought a bit about the "Minio" uploading part, is it used just as storage for the sources/tarball?

At the moment we are forcing the user to use S3 (natively, or via Minio). I think it could make sense to abstract this part and extend it to other providers, having just an _Uploader_ interface that could be binded to other external sources.

i.e.: if I'm using a GKE or AKS cluster maybe I want to use the blob storage provided by Google or Azure. Just food for thought, maybe I should tag @agracey :slightly_smiling_face:

**Comment by andreas-kupries** [comment]
Thank you. Do the GKE/AKS blob storages do not provide an S3 compatible API ? If they do we can use them as they are.

Not merging yet, there looks to be a true failed test

> when staging the same app with no blob defined
   /home/sles/actions-runner/_work/epinio/epinio/acceptance/api/v1/application_stage_test.go:100
    stages with the previous blob [It]

which looks to require a fix.

**Comment by andreas-kupries** [comment]
It was flake. CI :heavy_check_mark: now ...

**Comment by enrichman** [comment]
> Thank you. Do the GKE/AKS blob storages do not provide an S3 compatible API ? If they do we can use them as they are.

Ah, I didn't investigate that. IOt seems that Google does, while Azure not. But I think that if that's the case the priority will go down.

**Pull request merged**
