### PR TITLE
Support resource requests for staging jobs

### LINKED ISSUE #2286: Resources Requests for Staging Job
**Is your feature request related to a problem? Please describe.**

Currently the Staging job does not have Resources requests section.

For standard k8s clusters (eks managed nodes, gke standard), this allows the pod consume how much resource it wanna, and sometimes it make the node became unresponsive due the lack of resources.

For gke autopilot clusters, when resources requests is not specified, the gke sets the [default resource requests](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#compute-class-defaults), causing the staging job failing due BackoffLimitExceeded

**Describe the solution you'd like**

I thought in two possible solutions:

1 - Set a hard coded value on the stage job definition: https://github.com/epinio/epinio/blob/main/internal/api/v1/application/stage.go#L524)

2 - Expose this via helm-chart values.
    stagingJob:
      resources:
        requests:
          cpu: 
          memory:

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fix #2286 
Ref https://github.com/epinio/helm-charts/pull/439

feat:  staging job resource request support

### CODE REVIEW

**Comment by andreas-kupries** [comment]
Testing that the new facility operates as desired:

  - Install E with `--set server.stagingResourceRequests.cpu=100m --set server.stagingResourceRequests.memory=100M`
  - Use `kubectl get pod -o yaml .... ` to look at the YAML of the `epinio-server` pod and check that the `STAGING_RESOURCE_...` environment variables are set to the requested values.
  - Push an application and inspect the stage job pod to also have these values

Example server data
```
    - name: STAGING_RESOURCE_CPU
      value: 100m
    - name: STAGING_RESOURCE_MEMORY
      value: 100M
```

Example job data
```
spec:
  containers:
    - [...]
      resources:
        requests:
          cpu: 100m
          memory: 100M

```

**Review by thehejik — APPROVED** [review]
Works as expected.

**Versions**
Kubernetes Version: v1.26.5+k3s1
Epinio Server Version: v1.9.0-rc2-18-g89f196b1

**Validation**
* Deployed by using associated PR https://github.com/epinio/helm-charts/pull/439, following appended:
```
 --set server.stagingResourceRequests.cpu=100m --set server.stagingResourceRequests.memory=100M
```
* Epinio-server deployment patched to use epinio binary built from this PR, used `make patch-epinio-deployment`
* Checked environment of `epinio-server` deployment:
```
$ kubect get deploy  -n epinio epinio-server -o jsonpath='{..env}' | jq
...
  {
    "name": "STAGING_RESOURCE_CPU",
    "value": "100m"
  },
  {
    "name": "STAGING_RESOURCE_MEMORY",
    "value": "100M"
  }
...
```
* Pushed an app and checked its staging job:
```
$ kubectl get pod stage-workspace-sample-70bb266339423ee24e42c4426abd2f15cddrrlzs -n epinio -o yaml
...
resources:
  requests:
    cpu: 100m
    memory: 100M
...
```
* The deployed app itself doesn't have the resources set: `resources: {}`
* Input values validation check:
   - With `--set server.stagingResourceRequests.cpu=100X` - the helm installation fails on `CrashLoopBackOff` for `epinio-server` pod, log contains:
   ```
   ❌  bad cpu request for staging job: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
   ```
   - With `--set server.stagingResourceRequests.memory=a100hy` - the helm installation fails on `CrashLoopBackOff` for `epinio-server` pod, log contains:
   ```
   ❌  bad memory request for staging job: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
   ```
* User can set both resource types at once or just one of them

**Comment by andreas-kupries** [comment]
It should be possible to set both cpu and memory.

**Comment by thehejik** [comment]
Verified in epinio v1.9.0-rc3 according to the report above - all good

**Pull request merged**
