### PR TITLE
Add Mac M1 silicon (Darwin/ARM64) support to Makefile

### PR DESCRIPTION
**Pull request by thardeck**
This should also provide the Mac M1 binary with the next release.

### CODE REVIEW

**Review by andreas-kupries — DISMISSED** [review]

**Comment by andreas-kupries** [comment]
I rebased to the latest main now. Tried the new build targets. They result in the expected binaries and file types.

**Review by andreas-kupries — APPROVED** [review]
Re-approving.

**Comment by andreas-kupries** [comment]
The CI cli failure (`[It] lists all services belonging to all namespaces `) is known, some inter-test interference appearing under high concurrency. The change to the Makefile has nothing to with it. I uphold my approval.

**Comment by jimmykarily** [comment]
CI fail is irrelevant. Merging.

**Pull request merged**
