### PR TITLE
fixed missing support for edit of service (custom values, update/replace)

### LINKED ISSUE #2518: It's not possible to edit Service chart values/settings
Related issue: [#252 ](https://github.com/epinio/ui/issues/252)

Service/edit APIs to be provided.

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #2518

### CODE REVIEW

**Comment by enrichman** [comment]
There are some conflicts to resolve. One first thing is that I would change the `--remove` flag to `--unset`, to have the `--set/--unset` pair available.

**Comment by andreas-kupries** [comment]
Will resolve the conflicts.

**Comment by andreas-kupries** [comment]
> One first thing is that I would change the `--remove` flag to `--unset`, to have the `--set/--unset` pair available.

Note that making this change would make this different from the `configuration update` command which uses the same `--remove`/`--set` pair.

**Comment by andreas-kupries** [comment]
> > One first thing is that I would change the `--remove` flag to `--unset`, to have the `--set/--unset` pair available.
> 
> Note that making this change would make this different from the `configuration update` command which uses the same `--remove`/`--set` pair.

Finding https://github.com/spf13/pflag#mutating-or-normalizing-flag-names I will see if I can support the old `--remove` while switching to `--unset` going forward. That way we would have backward compatibility.

**Review by enrichman — APPROVED** [review]

**Pull request merged**
