### PR TITLE
Give gitea's postgresql container sufficient permissions

### LINKED ISSUE #641: Gitea PostgreSQL fails to create /bitnami/postgresql directory - permission denied
Following the k3d quickstart 
MacOS 
Docker CE 20.10.7
k3d v4.4.7
Single node using rancher.io/local-path storage driver (default)

Gitea fails to deploy. Specifically, the gitea postgres container fails to deploy with the following in the logs:
```
│ postgresql 12:29:51.56 INFO  ==> ** Starting PostgreSQL setup **                                                                                                     │
│ postgresql 12:29:51.57 INFO  ==> Validating settings in POSTGRESQL_* env vars..                                                                                      │
│ postgresql 12:29:51.58 INFO  ==> Loading custom pre-init scripts...                                                                                                  │
│ postgresql 12:29:51.58 INFO  ==> Initializing PostgreSQL database...                                                                                                 │
│ mkdir: cannot create directory ‘/bitnami/postgresql’: Permission denied                                                                                              │
│ postgresql 12:29:51.59 INFO  ==> Stopping PostgreSQL...
```

Not sure if this relates to https://github.com/epinio/epinio/issues/615, but as different platform logging here.

### PR DESCRIPTION
**Pull request by kkaempf**
Fixes #641

Signed-off-by: Klaus Kämpf <kkaempf@suse.de>

### CODE REVIEW

**Comment by kkaempf** [comment]
Ask mentioned on Slack, I fail to verify this under Windows. Following the discussion on #641 it should be a) the right fix and b) not do any harm. 🤞🏻

**Comment by agracey** [comment]
I'm pretty confident this does fix the issue. Using a binary build from this fork, installing Epinio deploys Gitea just fine but then fails when trying to pull "splatform/epinio-server:v0.0.21-58-gd87ca8e7"

**Comment by agracey** [comment]
Oh, found another issue that I'm betting is similar: 

`PS C:\Users\Andrew Gracey\Projects> kubectl logs gitea-0 -ngitea --all-containers=true
gitea-postgresql (10.43.119.48:5432) open
+ gitea migrate
2021/08/24 15:52:29 ...s/setting/setting.go:504:NewContext() [W] Custom config '/data/gitea/conf/app.ini' not found, ignore this if you're running first time
2021/08/24 15:52:29 ...s/setting/setting.go:688:NewContext() [F] Failed to create '/data/git/.ssh': mkdir /data/git: permission denied
+ gitea admin create-user --username 358bcae55119d6ef --password 22c99d72f9aebb4f --email admin@epinio.sh --admin --must-change-password=false
2021/08/24 15:52:29 ...s/setting/setting.go:504:NewContext() [W] Custom config '/data/gitea/conf/app.ini' not found, ignore this if you're running first time
2021/08/24 15:52:29 ...s/setting/setting.go:688:NewContext() [F] Failed to create '/data/git/.ssh': mkdir /data/git: permission denied
+ gitea admin change-password --username 358bcae55119d6ef --password 22c99d72f9aebb4f
2021/08/24 15:52:29 ...s/setting/setting.go:504:NewContext() [W] Custom config '/data/gitea/conf/app.ini' not found, ignore this if you're running first time
2021/08/24 15:52:29 ...s/setting/setting.go:688:NewContext() [F] Failed to create '/data/git/.ssh': mkdir /data/git: permission denied
Error from server (BadRequest): container "linkerd-init" in pod "gitea-0" is waiting to start: PodInitializing`

**Comment by andreas-kupries** [comment]
> but then fails when trying to pull "splatform/epinio-server:v0.0.21-58-gd87ca8e7"

The `-58-...` makes this a development build. I suspect you have to set it up like a development installation, i.e. 
https://github.com/epinio/epinio/blob/896c32e352758d639bd4fa6babdfdd26fb603f4b/docs/developer/howtos/development.md#installing-epinio

**Comment by agracey** [comment]
@andreas-kupries I got past that by editing the deployment while epinio was still waiting for readiness.

**Comment by agracey** [comment]
This whole issue goes away with a switch to minio/S3 :D

**Pull request merged**
