### PR TITLE
Release CI: Extended the set of artifacts to generate SBOMs for.

### LINKED ISSUE #2271: Missing SBOMs for Epinio binaries (only Windows)
We are not generating SBOMs for the binaries because of the missing `any` artifact type (https://goreleaser.com/customization/sbom/)

https://github.com/epinio/epinio/blob/main/.goreleaser.yml#L309-L317

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #2271

### CODE REVIEW

**Comment by andreas-kupries** [comment]
This seems to have broken the sandbox release

https://github.com/epinio/epinio/actions/runs/4913254983/jobs/8773226807?pr=2287#step:9:56

Retrying to see if that was a transient thing.

**Comment by andreas-kupries** [comment]
Definitely not transient. Now lets try other things.

**Comment by andreas-kupries** [comment]
and the sandbox is :heavy_check_mark: :)

**Comment by andreas-kupries** [comment]
Looking at the release output I cannot say if the result is better than before, or not.

**Review by enrichman — APPROVED** [review]

**Pull request merged**
