### PR TITLE
fix: drop deprecated apiextensions.k8s.io/v1beta1 CustomResourceDefinition

### LINKED ISSUE #204: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated
Deploying ServiceCatalog warns about `apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`:
```
🚢 Deploying ServiceCatalog...............................................W0309 14:53:10.077453  130688 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

### PR DESCRIPTION
**Pull request by kkaempf**
It was used in Tekton and kubernetes/cluster.go

fixes #204

### CODE REVIEW

**Review by rohitsakala — CHANGES_REQUESTED** [review]
I think you should run `make embed_files` since files in the `embedded-files` folder have changed.

**Comment by kkaempf** [comment]
> I think you should run `make embed_files` since files in the `embedded-files` folder have changed.

Right, thanks. However why do we track generated files (`statik.go`) in git? Those belong into a release tarball, but not git :thinking:

**Comment by andreas-kupries** [comment]
Quicker ramp up for developers without the tooling to generate it ?
(This is also a point for our docs-to-be, list the tooling we use, and how to get/install it)

**Comment by manno** [comment]
> Quicker ramp up for developers without the tooling to generate it ?
> (This is also a point for our docs-to-be, list the tooling we use, and how to get/install it)

`statik` is used in the Makefile, so without it, you can't even run `make build`.  That target even tries to install it (every time).

**Comment by manno** [comment]
gitlint spotting the important things 😈 : `1: T1 Title exceeds max length (74>72): "fix: drop deprecated apiextensions.k8s.io/v1beta1 CustomResourceDefinition"`

**Review by manno — DISMISSED** [review]
This will not pass unless statik.go is generated. We might want to change that in a different story, so acceptance tests generate the file and we don't commit generated code.

I also can't push the updated and rebased branch and tests fail when testing locally. Might be my setup though.

**Comment by jimmykarily** [comment]
Superseded by #318

**Pull request closed without merging**
